---
kind: pipeline
name: compile-on-amd64

platform:
  arch: amd64

steps:
- name: fetch
  image: alpine/git
  commands:
  - wget https://nginx.org/download/nginx-1.18.0.tar.gz
  - tar -zxf nginx-1.18.0.tar.gz
  - git clone --single-branch --branch v0.33 https://github.com/openresty/headers-more-nginx-module.git

- name: compile
  image: gcc
  commands:
  - cd nginx-1.18.0
  - ./configure --add-dynamic-module=../headers-more-nginx-module 
  - make
  - ls -lh objs/

- name: publish
  image: plugins/github-release
  settings:
    overwrite: yes
    api_key:
      from_secret: github_token
    checksum:
      - md5
      - sha1
      - sha256
      - sha512
      - adler32
      - crc32
    files:
      - objs/*

trigger:
  event:
  - tag
