---
kind: pipeline
name: compile-on-amd64

platform:
  arch: amd64
  os: linux

workspace:
  path: /drone/src

environment:
  NGINX_VERSION: 1.18.0
  MORE_HEADER_MODULE_VERSION: v0.33

steps:
- name: fetch
  image: alpine/git
  commands:
  - export NGINX_VERSION="$(cat NGINX_VERSION.txt)"
  - export MORE_HEADER_MODULE_VERSION="$(cat MORE_HEADER_MODULE_VERSION.txt)"
  - wget "https://nginx.org/download/nginx-$NGINX_VERSION.tar.gz"
  - tar -zxf nginx-$NGINX_VERSION.tar.gz
  - mv nginx-$NGINX_VERSION nginx
  - git clone --single-branch --branch "$MORE_HEADER_MODULE_VERSION" https://github.com/openresty/headers-more-nginx-module.git

- name: compile
  image: gcc
  commands:
  - cd nginx
  - ./configure --add-dynamic-module=../headers-more-nginx-module --with-compat
  - make modules

- name: publish
  image: plugins/github-release
  settings:
    overwrite: yes
    api_key:
      from_secret: github_token
    checksum:
      - md5
      - sha1
      - sha256
      - sha512
      - adler32
      - crc32
    note: >
      Nginx: $(cat /drone/src/NGINX_VERSION.txt)
      headers-more-nginx-module: $(cat MORE_HEADER_MODULE_VERSION.txt)
    files:
      - /drone/src/nginx/objs/ngx_http_headers_more_filter_module.so
  when:
    event: tag

- name: send telegram notification
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: telegram_token
    to:
      from_secret: telegram_id
    format: html
    message: >
      {{#success build.status}}
        build <a href="https://cloud.drone.io/bkayranci/nginx-more-header-module/{{build.number}}">{{build.number}}</a> succeeded. Good job.
      {{else}}
        build <a href="https://cloud.drone.io/bkayranci/nginx-more-header-module/{{build.number}}">{{build.number}}</a> failed. Fix me please.
      {{/success}}
  when:
    status:
    - success
    - failure
