---
kind: pipeline
name: compile-on-amd64

platform:
  arch: amd64
  os: linux

workspace:
  path: /drone/src

steps:
- name: fetch
  image: alpine/git
  commands:
  - export NGINX_VERSION="$(cat NGINX_VERSION.txt)"
  - export MORE_HEADER_MODULE_VERSION="$(cat MORE_HEADER_MODULE_VERSION.txt)"
  - wget "https://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz"
  - tar -zxf nginx-${NGINX_VERSION}.tar.gz
  - git clone --single-branch --branch "${MORE_HEADER_MODULE_VERSION}" https://github.com/openresty/headers-more-nginx-module.git

- name: compile
  image: gcc
  commands:
  - export NGINX_VERSION="$(cat NGINX_VERSION.txt)"
  - cd nginx-${NGINX_VERSION}
  - ./configure --add-dynamic-module=../headers-more-nginx-module --with-compat
  - make modules

- name: publish
  image: plugins/github-release
  settings:
    overwrite: yes
    api_key:
      from_secret: github_token
    checksum:
      - md5
      - sha1
      - sha256
      - sha512
      - adler32
      - crc32
    files:
      - objs/ngx_http_headers_more_filter_module.so

- name: send telegram notification
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: telegram_token
    to:
      from_secret: telegram_id
    message: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}
