---
kind: pipeline
name: compile-on-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: fetch
  image: alpine/git
  volumes:
  - name: shared-volume
    path: /root/.shared-volume
  commands:
  - cd /root/.shared-volume
  - wget https://nginx.org/download/nginx-1.18.0.tar.gz
  - tar -zxf nginx-1.18.0.tar.gz
  - git clone --single-branch --branch v0.33 https://github.com/openresty/headers-more-nginx-module.git

- name: compile
  image: gcc
  volumes:
  - name: shared-volume
    path: /root/.shared-volume
  commands:
  - apt-get update
  - apt-get -y install libgeoip-dev
  - cd /root/.shared-volume/nginx-1.18.0
  - ./configure --add-dynamic-module=../headers-more-nginx-module --prefix=/etc/nginx --conf-path=/etc/nginx/nginx.conf --sbin-path=/usr/bin/nginx --pid-path=/run/nginx.pid --lock-path=/run/lock/nginx.lock --user=http --group=http --http-log-path=/var/log/nginx/access.log --error-log-path=stderr --http-client-body-temp-path=/var/lib/nginx/client-body --http-proxy-temp-path=/var/lib/nginx/proxy --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-cc-opt='-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -D_FORTIFY_SOURCE=2' --with-ld-opt=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now --with-compat --with-debug --with-file-aio --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_degradation_module --with-http_flv_module --with-http_geoip_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-pcre-jit --with-stream --with-stream_geoip_module --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-threads
  - make
  - pwd
  - ls -lh objs/

- name: publish
  image: plugins/github-release
  volumes:
  - name: shared-volume
    path: /root/.shared-volume
  settings:
    overwrite: yes
    api_key:
      from_secret: github_token
    checksum:
      - md5
      - sha1
      - sha256
      - sha512
      - adler32
      - crc32
    files:
      - /root/.shared-volume/nginx-1.18.0/objs/ngx_http_headers_more_filter_module.so

trigger:
  event:
  - tag

volumes:
- name: shared-volume
  temp: {}